# Site
name: "isthisLee's blog"
title: "isthisLee's tech blog(web 개발 블로그, javascript)"
description: "isthisLee(이건희)의 개발(develop) 블로그(blog)입니다. 주로 WEB 기술에 관련된 이슈(issue)와 공부(study, til)한 내용을 정리하고 있습니다."
home_description: "이슈, 공부한 내용을 정리하는 블로그입니다."
logo: "assets/images/darkmodeparrot.gif"
favicon: "aassets/images/darkmodeparrot.gif"
baseurl: ""
google_tagmanager: "GTM-W4DFQ56"
# disqus: "isthis" - 댓글 기능 giscus로 변경
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  isthis:
    name: isthisLee
    display_name: 이건희
    gravatar: b3007b17990548abf8b6d7e0dd7d5294
    email: rjsgmldnwn@gmail.com
    web: https://isthislee.com
    github: https://github.com/IsthisLee
    description: "초보 개발자입니다. 이슈 및 공부한 내용을 정리하고 있습니다. 피드백 환영합니다 :)"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-9923968903493294"
adsense-data-ad-slot: "7185027430"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
