# Site
name: "isthis's blog"
title: "isthis's blog"
description: "이슈, 공부한 내용을 정리하는 블로그입니다."
logo: "assets/images/darkmodeparrot.gif"
favicon: "aassets/images/darkmodeparrot.gif"
baseurl: "/Blog"
google_analytics: "UA-46278016-1"
disqus: "isthis"
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  isthis:
    name: isthisLee
    display_name: 이건희
    gravatar: b3007b17990548abf8b6d7e0dd7d5294
    email: rjsgmldnwn@gmail.com
    web: https://github.com/IsthisLee
    description: "안녕하세요. 초보 개발자입니다. 이슈 및 공부한 내용을 정리하고 있습니다. 피드백 환영합니다 :)"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

# Pagination
paginate: 9
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
